# Generated by Django 5.1.2 on 2024-10-22 04:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_filemeta_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemeta',
            name='chunk_number',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filemeta',
            name='chunks_processed',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filemeta',
            name='folder_path',
            field=models.CharField(default='folder', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filemeta',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='filemeta',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadefile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
